### ISSUE TITLE
Update README example to use 'Array.from()'

### ISSUE THREAD

**Issue by cyclecycle** [derhuerst/flatten-overlapping-ranges#2]
Hi, 

The example is in the README is out of date. Took me a little while to figure out why I wasn't getting the output array.

Thanks a lot for this module, just what I needed :)

**Comment by derhuerst** [comment]
Thanks for the hint, PR welcome! Please just add `Array.from` in the `console.log` line.

Glad I could help others with this module. Next time, it will save time as well. 😉

**Comment by derhuerst** [comment]
Closing as #3 is merged.

**Comment by derhuerst** [comment]
Published as `flatten-overlapping-ranges@1.0.1`. :shipit:
